package com.platform.prism.enums;

public enum ConsultationType {
    NUTRITIONAL,
    WELLNESS,
    DIABETES,
    BLOOD_PRESSURE,
    CARDIAC,
    MENTAL_HEALTH,
    MEDICATION_MANAGEMENT,
    ALLERGY_MANAGEMENT,
    IMMUNIZATION,
    THYROID,
    WEIGHT_MANAGEMENT,
    STRESS_MANAGEMENT,
    SLEEP_HEALTH,
    PHYSICAL_FITNESS,
    WOMENS_HEALTH,
    MENS_HEALTH
}
