spring:
  application:
    name: prism
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/prism
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "Base schema"
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health, info
logging:
  level:
    org.springframework.security: DEBUG