spring:
  security:
    user:
      name: test
      password: test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# Development configuration
cors:
  allowed-origins: http://localhost:3000

# Logging configuration for development
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
